create database india_ecomm_sales;
use india_ecomm_sales;
SELECT * FROM customer LIMIT 20;
SELECT * FROM orders LIMIT 20;

/*Q1-Find the total number of orders placed on each e-commerce platform , sorted from highest to lowest.*/
SELECT 
    platform, COUNT(order_id) AS total_order
FROM
    orders
GROUP BY platform
ORDER BY total_order DESC;

/*Q2-Retrieve all order IDs where the revenue is greater than ₹1000000 and the order was not returned*/
SELECT 
    order_id, revenue
FROM
    orders
WHERE
    revenue > 1000000 AND returned = 0
ORDER BY revenue DESC;

/*Q3-From the customers table, find the total number of registered customers grouped by their gender.*/
SELECT 
    gender, COUNT(gender) AS no_customer
FROM
    customer
GROUP BY gender;

/*Q4-join both tables to find the total revenue and total profit generated by top 5 customers.
 Display customer_id, customer name, total revenue, and total profit.*/
SELECT 
    c.customer_id,
    c.name,
    SUM(o.revenue) AS total_revenue,
    SUM(o.profit) AS total_profit
FROM
    customer c
        INNER JOIN
    orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id , c.name
ORDER BY total_revenue DESC
LIMIT 5;

/*Q5-Which Indian state has generated the highest Total Gross Merchandise Value (GMV)? List the top 5 states along with their total GMV.*/
SELECT 
    state, SUM(gmv) AS total_gmv
FROM
    orders
GROUP BY state
ORDER BY total_gmv DESC
LIMIT 5;

/*Q6-Calculate the average margin_pct for each product category. Filter out categories where the average margin is below $20\%$ ($0.20$).SQL*/
SELECT 
    category, AVG(margin_pct) AS avg_margin
FROM
    orders
GROUP BY category
HAVING AVG(margin_pct) <= 0.20;

/*Q7-Calculate the return rate percentage for each product category*/
SELECT 
    category,
    count(order_id) AS total_order,
    SUM(returned) AS total_return,
    (SUM(returned) * 100 / count(order_id)) AS pct_return
FROM
    orders
GROUP BY category;

/*Q8-For each Indian state, find the specific city that generated the highest total profit.*/
WITH CityProfit AS (
    SELECT 
        state, 
        city, 
        SUM(profit) AS total_profit,
        DENSE_RANK() OVER (PARTITION BY state ORDER BY SUM(profit) DESC) AS rnk
    FROM orders
    GROUP BY state, city
)
SELECT 
    state, 
    city, 
    total_profit
FROM CityProfit
WHERE rnk = 1
ORDER BY total_profit DESC;

/*Q9-Track the total revenue month-on-month for the year 2023.
 Display order_year, order_month, current month's revenue, and show a running cumulative total of revenue for that year.*/
SELECT 
    order_year,
    order_month,
    SUM(revenue) AS monthly_revenue,
    SUM(SUM(revenue)) OVER (PARTITION BY order_year ORDER BY order_month) AS running_total_revenue
FROM orders
WHERE order_year = 2023
GROUP BY order_year, order_month
ORDER BY order_month;

/*Q10-Find the absolute top-performing (highest total profit) product within every product category 
to identify your primary inventory winners.*/
WITH RankedProducts AS (
    SELECT 
        category,
        product,
        SUM(profit) AS total_product_profit,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY SUM(profit) DESC) AS profit_rank
    FROM Orders
    GROUP BY category, product
)
SELECT 
    category,
    product,
    total_product_profit
FROM RankedProducts
WHERE profit_rank = 1
ORDER BY total_product_profit DESC;